// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBD0eZcQyvGYVOiWGQEfcWNUIG3JrsBaiY',
    appId: '1:573974583358:web:0623834fff7a64d01d596f',
    messagingSenderId: '573974583358',
    projectId: 'khata-king',
    authDomain: 'khata-king.firebaseapp.com',
    storageBucket: 'khata-king.firebasestorage.app',
    measurementId: 'G-CNQGRXL7M8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtroIkaXHRm7ZcukkuMAPJMi4OK7NaKkc',
    appId: '1:573974583358:android:f969a002b97bdc731d596f',
    messagingSenderId: '573974583358',
    projectId: 'khata-king',
    storageBucket: 'khata-king.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDInIe6VaxqAt4gaYHx6CxeozUH2AjBtOM',
    appId: '1:573974583358:ios:87b14940ac65cc5a1d596f',
    messagingSenderId: '573974583358',
    projectId: 'khata-king',
    storageBucket: 'khata-king.firebasestorage.app',
    iosBundleId: 'com.example.khataKing',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDInIe6VaxqAt4gaYHx6CxeozUH2AjBtOM',
    appId: '1:573974583358:ios:87b14940ac65cc5a1d596f',
    messagingSenderId: '573974583358',
    projectId: 'khata-king',
    storageBucket: 'khata-king.firebasestorage.app',
    iosBundleId: 'com.example.khataKing',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBD0eZcQyvGYVOiWGQEfcWNUIG3JrsBaiY',
    appId: '1:573974583358:web:86da694245eeac491d596f',
    messagingSenderId: '573974583358',
    projectId: 'khata-king',
    authDomain: 'khata-king.firebaseapp.com',
    storageBucket: 'khata-king.firebasestorage.app',
    measurementId: 'G-CPCQE7KH1P',
  );
}
